title: Archer Zhang
email: archer.xn@gmail.com
description: "stuff"
baseurl: /
permalink: /:title
logo_url: https://avatars1.githubusercontent.com/u/9267198?s=460&v=4
url: "https://archerzhang.me"
twitter_username: a_zhng
linkedin_username: a-zhng
github_username:  Azhng
author_name: Archer Zhang

# Build settings
highlighter:        rouge
sass:
  style: :compressed
markdown: kramdown
kramdown:
    input:          GFM
theme: the-plain
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: heiswayi/the-plain
include: [ "BingSiteAuth.xml" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
layout: "post"
